apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: internal-proxy
  delay:
    latency: "100ms"
    correlation: "25"
    jitter: "10ms"
  duration: "5m"