apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: targeted-pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: health-check
  duration: "10s"
  gracePeriod: 0